

version: '3'
services:
  selenium-hub:
    image: selenium/hub:4.18.1-20240224
    environment:
      - SE_NODE_MAX_SESSIONS=5
    ports:
      - "4444:4444"
  chrome:
      image: selenium/node-chrome:4.18.1-20240224
      shm_size: 2gb
      depends_on:
        - selenium-hub
      environment:
        - SE_NODE_MAX_SESSIONS=5
        - SE_EVENT_BUS_HOST=selenium-hub
        - SE_EVENT_BUS_PUBLISH_PORT=4442
        - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
  scraper:
    build: .
    depends_on:
      - db
    volumes:
      - .:/app
   # command: scrapy crawl sreality
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
  web:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db

